name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print Hi
        run: echo " Helloooo"
      - name: print byee
        run: echo " see you later"
